"""
c_code_generator.py
-------------------
FOLDER : D:\Auto\claude-autosar-integration\src\
FILE   : src\c_code_generator.py

Layer 3 (MATLAB-free) — Generates AUTOSAR-compliant C code stubs
from ANY ARXML file — whether generated by this pipeline, downloaded
from the internet, or exported from Vector DaVinci / ETAS ISOLAR.

Produces 4 files:
    Rte_Types.h        — AUTOSAR base type definitions
    Rte_<swc>.h        — RTE API declarations
    <swc>.h            — SWC component header
    <swc>.c            — Runnable skeletons (fill in your logic)

Two usage modes:

    Mode A — from ARXML files directly (generic, works on any ARXML):
        from src.c_code_generator import CCodeGenerator
        gen = CCodeGenerator.from_arxml(
            comp  = Path("component.arxml"),
            dt    = Path("datatypes.arxml"),
            iface = Path("interfaces.arxml"),
            output_dir = Path("output/c_code")
        )
        files = gen.generate_all()

    Mode B — from SWCSpec (used when coming from Claude pipeline):
        from src.c_code_generator import CCodeGenerator
        gen = CCodeGenerator.from_spec(spec, output_dir=Path("output/c_code"))
        files = gen.generate_all()

CLI:
    python -m src.c_code_generator --arxml output/SpeedSensor
    python -m src.c_code_generator --test
"""

import logging
import sys
from pathlib import Path
from datetime import datetime
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

# ── AUTOSAR C type mapping ─────────────────────────────────────────────
C_TYPE_MAP = {
    "uint8":   "uint8",
    "uint16":  "uint16",
    "uint32":  "uint32",
    "sint8":   "sint8",
    "sint16":  "sint16",
    "float32": "float32",
    # fallback for types not in our map
}

C_PRIMITIVE_MAP = {
    "uint8":   "unsigned char",
    "uint16":  "unsigned short",
    "uint32":  "unsigned int",
    "sint8":   "signed char",
    "sint16":  "signed short",
    "float32": "float",
}


# ── Internal data model (ARXML-parsed) ───────────────────────────────
@dataclass
class PortInfo:
    name: str
    direction: str          # "P" or "R"
    interface_name: str
    data_element: str
    data_type: str          # e.g. "uint16"


@dataclass
class AccessInfo:
    port: str
    mode: str               # "read" or "write"


@dataclass
class RunnableInfo:
    name: str
    period_ms: int          # -1=init, 0=event, >0=periodic
    accesses: list[AccessInfo] = field(default_factory=list)


@dataclass
class SWCInfo:
    """Generic SWC representation parsed from ARXML or SWCSpec."""
    swc_name: str
    ports: list[PortInfo]
    runnables: list[RunnableInfo]


# ── ARXML Parser ─────────────────────────────────────────────────────
class ARXMLParser:
    """
    Parses AUTOSAR ARXML files into SWCInfo.
    Works on ANY valid ARXML — not just files generated by this pipeline.
    """

    @staticmethod
    def parse(comp_path: Path, dt_path: Path, iface_path: Path) -> SWCInfo:
        """
        Parse 3 ARXML files and return a SWCInfo object.
        Works on ANY valid AUTOSAR ARXML.
        """
        import autosarfactory.autosarfactory as af
        af.reinit()
        af.read([str(comp_path), str(dt_path), str(iface_path)])

        root = af.get_root()

        # ── Find the SWC ─────────────────────────────────────────────
        swc_nodes = af.get_all_instances(root, af.ApplicationSwComponentType)
        if not swc_nodes:
            raise ValueError("No ApplicationSwComponentType found in ARXML files")

        swc_node = swc_nodes[0]
        swc_name = swc_node.name
        logger.info("Parsing SWC: %s", swc_name)

        # ── Parse ports ──────────────────────────────────────────────
        ports = []
        all_ports = swc_node.get_ports() or []

        for port in all_ports:
            port_type = type(port).__name__
            direction = "P" if "PPort" in port_type else "R"

            if direction == "P":
                iface = port.get_providedInterface()
            else:
                iface = port.get_requiredInterface()

            if iface is None:
                continue

            de_list = iface.get_dataElements() or []
            de_name = de_list[0].name if de_list else "DataElement"
            dt = ARXMLParser._resolve_type(de_list[0] if de_list else None)
            ports.append(PortInfo(
                name=port.name,
                direction=direction,
                interface_name=iface.name,
                data_element=de_name,
                data_type=dt,
            ))

        # ── Parse runnables ───────────────────────────────────────────
        runnables = []
        ibs = af.get_all_instances(root, af.SwcInternalBehavior)

        for ib in ibs:
            runnable_nodes = af.get_all_instances(ib, af.RunnableEntity)
            timing_events  = af.get_all_instances(ib, af.TimingEvent)
            init_events    = af.get_all_instances(ib, af.InitEvent)

            # Build event lookup: runnable_name -> period_ms
            period_map = {}
            for te in timing_events:
                ref = te.get_startOnEvent()
                if ref:
                    period_s = te.get_period()
                    period_map[ref.name] = int(float(period_s) * 1000) if period_s else 10
            for ie in init_events:
                ref = ie.get_startOnEvent()
                if ref:
                    period_map[ref.name] = -1

            for r in runnable_nodes:
                period_ms = period_map.get(r.name, 10)
                runnables.append(RunnableInfo(
                    name=r.name,
                    period_ms=period_ms,
                    accesses=[],
                ))

        # Infer port accesses for periodic runnables
        # R-port = read access, P-port = write access
        # Only assign to periodic runnables (not init)
        for r in runnables:
            if r.period_ms != -1:  # skip init runnables
                for p in ports:
                    mode = "read" if p.direction == "R" else "write"
                    r.accesses.append(AccessInfo(port=p.name, mode=mode))

        logger.info("Parsed: %d ports, %d runnables", len(ports), len(runnables))
        return SWCInfo(swc_name=swc_name, ports=ports, runnables=runnables)

    @staticmethod
    def _resolve_type(de_node) -> str:
        """Resolve data element type to our C type map key."""
        if de_node is None:
            return "uint8"
        try:
            type_node = de_node.get_type()
            if type_node:
                name = type_node.name.lower().replace("_t", "")
                for key in C_TYPE_MAP:
                    if key in name:
                        return key
        except Exception:
            pass
        return "uint8"

    @staticmethod
    def _get_period_ms(ib, runnable_name: str) -> int:
        """Find the period_ms for a runnable by checking its trigger events."""
        try:
            # Check TimingEvents
            events = ib.get_events() or []
            for ev in events:
                ref = ev.get_startOnEvent()
                if ref and ref.name == runnable_name:
                    ev_type = type(ev).__name__
                    if "InitEvent" in ev_type:
                        return -1
                    if "TimingEvent" in ev_type:
                        period_s = ev.get_period()
                        if period_s is not None:
                            return int(float(period_s) * 1000)
                    if "BackgroundEvent" in ev_type:
                        return 0
        except Exception:
            pass
        return 10  # default 10ms if can't determine


# ── Main Generator ────────────────────────────────────────────────────
class CCodeGenerator:
    """
    Generates AUTOSAR C code stubs from either ARXML files or SWCSpec.

    Use CCodeGenerator.from_arxml() for generic ARXML input.
    Use CCodeGenerator.from_spec() when coming from the Claude pipeline.
    """

    def __init__(self, swc_info: SWCInfo, output_dir: Path):
        self.info = swc_info
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        self.rte_types_path = self.output_dir / "Rte_Types.h"
        self.rte_swc_path   = self.output_dir / f"Rte_{self.info.swc_name}.h"
        self.swc_h_path     = self.output_dir / f"{self.info.swc_name}.h"
        self.swc_c_path     = self.output_dir / f"{self.info.swc_name}.c"

    # ── Factory methods ───────────────────────────────────────────────
    @classmethod
    def from_arxml(
        cls,
        comp: Path,
        dt: Path,
        iface: Path,
        output_dir: Path,
    ) -> "CCodeGenerator":
        """
        Create generator from ARXML files.
        Works on ANY valid AUTOSAR ARXML — not just files from this pipeline.
        """
        logger.info("Parsing ARXML files ...")
        swc_info = ARXMLParser.parse(comp, dt, iface)
        return cls(swc_info, output_dir)

    @classmethod
    def from_spec(cls, spec, output_dir: Path) -> "CCodeGenerator":
        """
        Create generator from a SWCSpec Pydantic model.
        Used when coming from the Claude API pipeline.
        """
        ports = [
            PortInfo(
                name=p.name,
                direction=p.direction,
                interface_name=p.interface_name,
                data_element=p.data_element,
                data_type=p.data_type,
            )
            for p in spec.ports
        ]
        runnables = [
            RunnableInfo(
                name=r.name,
                period_ms=r.period_ms,
                accesses=[
                    AccessInfo(port=a.port, mode=a.mode)
                    for a in r.accesses
                ],
            )
            for r in spec.runnables
        ]
        swc_info = SWCInfo(
            swc_name=spec.swc_name,
            ports=ports,
            runnables=runnables,
        )
        return cls(swc_info, output_dir)

    # ── Public ────────────────────────────────────────────────────────
    def generate_all(self) -> list[Path]:
        """Generate all 4 C files. Returns list of file paths."""
        logger.info("Generating C code for: %s", self.info.swc_name)
        self._gen_rte_types()
        self._gen_rte_header()
        self._gen_swc_header()
        self._gen_swc_source()
        logger.info("C code complete -> %s", self.output_dir)
        return [
            self.rte_types_path,
            self.rte_swc_path,
            self.swc_h_path,
            self.swc_c_path,
        ]

    # ── Rte_Types.h ───────────────────────────────────────────────────
    def _gen_rte_types(self):
        unique_types = sorted({p.data_type for p in self.info.ports})
        lines = [
            self._header("Rte_Types.h", "AUTOSAR base type definitions"),
            "#ifndef RTE_TYPES_H",
            "#define RTE_TYPES_H",
            "",
            "#include <stdint.h>",
            "",
            "/* AUTOSAR primitive type definitions (R22-11) */",
        ]
        for dt, ct in C_PRIMITIVE_MAP.items():
            lines.append(f"typedef {ct:<20} {dt};")
        lines += [
            "",
            "/* Standard return type */",
            "typedef unsigned char  Std_ReturnType;",
            "#define E_OK     ((Std_ReturnType)0x00U)",
            "#define E_NOT_OK ((Std_ReturnType)0x01U)",
            "",
            f"/* Implementation types for {self.info.swc_name} */",
        ]
        for dt in unique_types:
            lines.append(f"typedef {dt:<20} {dt}_T;")
        lines += ["", "#endif /* RTE_TYPES_H */", ""]
        self.rte_types_path.write_text("\n".join(lines), encoding="utf-8", errors="replace")
        logger.info("    %s", self.rte_types_path.name)

    # ── Rte_<swc>.h ───────────────────────────────────────────────────
    def _gen_rte_header(self):
        swc = self.info.swc_name
        guard = f"RTE_{swc.upper()}_H"
        port_map = {p.name: p for p in self.info.ports}
        lines = [
            self._header(f"Rte_{swc}.h", f"RTE API for {swc}"),
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            '#include "Rte_Types.h"',
            "",
        ]
        for runnable in self.info.runnables:
            if not runnable.accesses:
                continue
            lines.append(f"/* {runnable.name} */")
            for acc in runnable.accesses:
                port = port_map.get(acc.port)
                if not port:
                    continue
                ct = C_TYPE_MAP.get(port.data_type, "uint8")
                if acc.mode == "read":
                    fn = f"Rte_IRead_{runnable.name}_{port.name}_{port.data_element}"
                    lines.append(f"#define {fn}() \\")
                    lines.append(
                        f"    (*({ct}*)Rte_Inst_{swc}"
                        f".{port.name}->{port.data_element})"
                    )
                else:
                    fn = f"Rte_IWrite_{runnable.name}_{port.name}_{port.data_element}"
                    lines.append(f"#define {fn}(data) \\")
                    lines.append(
                        f"    (*({ct}*)Rte_Inst_{swc}"
                        f".{port.name}->{port.data_element} = (data))"
                    )
                lines.append("")
        lines += [f"#endif /* {guard} */", ""]
        self.rte_swc_path.write_text("\n".join(lines), encoding="utf-8", errors="replace")
        logger.info("    %s", self.rte_swc_path.name)

    # ── <swc>.h ───────────────────────────────────────────────────────
    def _gen_swc_header(self):
        swc = self.info.swc_name
        guard = f"{swc.upper()}_H"
        lines = [
            self._header(f"{swc}.h", f"Header for {swc}"),
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            '#include "Rte_Types.h"',
            f'#include "Rte_{swc}.h"',
            "",
            f"/* {swc} runnable entry points */",
        ]
        for r in self.info.runnables:
            lines.append(f"extern void {swc}_{r.name}(void);")
        lines += ["", f"#endif /* {guard} */", ""]
        self.swc_h_path.write_text("\n".join(lines), encoding="utf-8", errors="replace")
        logger.info("    %s", self.swc_h_path.name)

    # ── <swc>.c ───────────────────────────────────────────────────────
    def _gen_swc_source(self):
        swc = self.info.swc_name
        port_map = {p.name: p for p in self.info.ports}
        lines = [
            self._header(f"{swc}.c", f"Runnable implementations for {swc}"),
            f'#include "{swc}.h"',
            "",
        ]
        for runnable in self.info.runnables:
            if runnable.period_ms == -1:
                trigger = "Init — called once at ECU startup"
            elif runnable.period_ms == 0:
                trigger = "Event-triggered"
            else:
                trigger = f"Periodic — every {runnable.period_ms}ms"

            lines += [
                "/**",
                f" * {swc}_{runnable.name} — {trigger}",
            ]
            for acc in runnable.accesses:
                p = port_map.get(acc.port)
                if p:
                    verb = "reads" if acc.mode == "read" else "writes"
                    lines.append(f" * {verb} {p.name}.{p.data_element} ({p.data_type})")
            lines += [" */", f"void {swc}_{runnable.name}(void)", "{"]

            for acc in runnable.accesses:
                port = port_map.get(acc.port)
                if not port:
                    continue
                ct = C_TYPE_MAP.get(port.data_type, "uint8")
                if acc.mode == "read":
                    fn = (f"Rte_IRead_{runnable.name}_"
                          f"{port.name}_{port.data_element}")
                    lines += [
                        f"    {ct} {port.data_element} = {fn}();",
                        f"    (void){port.data_element};  /* TODO: use value */",
                        "",
                    ]
                else:
                    fn = (f"Rte_IWrite_{runnable.name}_"
                          f"{port.name}_{port.data_element}")
                    lines += [
                        f"    {ct} {port.data_element} = ({ct})0;  /* TODO: set value */",
                        f"    {fn}({port.data_element});",
                        "",
                    ]

            if not runnable.accesses:
                lines.append("    /* TODO: implement */")
            lines += ["}", ""]

        self.swc_c_path.write_text("\n".join(lines), encoding="utf-8", errors="replace")
        logger.info("    %s", self.swc_c_path.name)

    def _header(self, filename: str, desc: str) -> str:
        return "\n".join([
            "/**",
            f" * @file  {filename}",
            f" * @brief {desc}",
            f" * @swc   {self.info.swc_name}",
            f" * @gen   claude-autosar-bridge",
            f" * @date  {self.timestamp}",
            " * AUTO-GENERATED - DO NOT EDIT",
            " */", "",
        ])


# ── CLI ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    args = sys.argv[1:]

    # --arxml <folder>  : read ARXML from folder, generate C code
    if "--arxml" in args:
        idx = args.index("--arxml")
        folder = Path(args[idx + 1])
        comp  = folder / "component.arxml"
        dt    = folder / "datatypes.arxml"
        iface = folder / "interfaces.arxml"

        if not all(p.exists() for p in [comp, dt, iface]):
            print(f"[FAIL] Missing ARXML files in {folder}")
            print(f"       Expected: component.arxml, datatypes.arxml, interfaces.arxml")
            sys.exit(1)

        out = folder / "c_code"
        gen = CCodeGenerator.from_arxml(comp, dt, iface, out)
        paths = gen.generate_all()
        print(f"\n[OK] Generated {len(paths)} files in {out}:")
        for p in paths:
            print(f"     {p.name}  ({p.stat().st_size} bytes)")
        sys.exit(0)

    # --test : use hardcoded SpeedSensor spec
    from src.models import SWCSpec
    print("\n== CCodeGenerator test ==\n")

    spec = SWCSpec(**{
        "swc_name": "SpeedSensor",
        "category": "APPLICATION",
        "ports": [{
            "name": "SpeedPort",
            "direction": "R",
            "interface_name": "SpeedSensorInterface",
            "data_element": "VehicleSpeed",
            "data_type": "uint16",
        }],
        "runnables": [
            {"name": "Run10ms", "period_ms": 10,
             "accesses": [{"port": "SpeedPort", "mode": "read"}]},
            {"name": "InitSpeedSensor", "period_ms": -1, "accesses": []},
        ],
        "init_runnable": "InitSpeedSensor",
    })

    out = Path("output/test_speed_sensor/c_code")
    gen = CCodeGenerator.from_spec(spec, out)
    paths = gen.generate_all()

    print(f"[OK] Generated {len(paths)} files:\n")
    for p in paths:
        print(f"{'='*55}")
        print(f"  {p.name}")
        print(f"{'='*55}")
        print(p.read_text())

    # Also test from_arxml using our generated files
    print("\n== Testing from_arxml (reads ARXML directly) ==\n")
    arxml_dir = Path("output/test_speed_sensor")
    if all((arxml_dir / f).exists() for f in
           ["component.arxml", "datatypes.arxml", "interfaces.arxml"]):
        out2 = arxml_dir / "c_code_from_arxml"
        gen2 = CCodeGenerator.from_arxml(
            arxml_dir / "component.arxml",
            arxml_dir / "datatypes.arxml",
            arxml_dir / "interfaces.arxml",
            out2,
        )
        paths2 = gen2.generate_all()
        print(f"[OK] from_arxml generated {len(paths2)} files in {out2}")
        for p in paths2:
            print(f"     {p.name}  ({p.stat().st_size} bytes)")
    else:
        print("[SKIP] ARXML files not found — run python -m src.arxml_generator first")
